---
- name: Install necesary packages
  apt:
    name:
      - binutils
      - make
      - patch
      - dkms
      - dkms
      - gcc
      - qemu-kvm
      - libvirt-clients
      - libvirt-daemon-system
      - bridge-utils
      - virt-manager
    force_apt_get: yes

- name: Gnome installation
  apt:
    name:
      - ubuntu-gnome-desktop
      - gnome-shell
    force_apt_get: yes
  when: gnome|bool

- name: VirtualBox Install
  block:

    - name: Add virtualbox repo key
      become: true
      apt_key:
        url: "{{ virtualboxkey }}"
        state: present

    - name: Add repo virtualbox
      apt_repository:
        repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
        state: present

    - name: "Install VirtualBox"
      apt:
        name:
          - virtualbox-6.0
        state: present
        update_cache: yes
        force_apt_get: yes

    - name: adding existing user to group
      user:
        name: "{{ user }}"
        groups: vboxusers
        append: yes

    - name: VBOX setup script
      shell: /usr/lib/virtualbox/vboxdrv.sh setup

  when: vbox|bool

- name: Install basic applications
  apt:
    name:
      - git
      - zsh
      - wget
      - curl
      - snapd
      - vim
      - vagrant
      # - vlc
      - gnome-tweak-tool
      - terminator
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Install Numix theme
  apt:
    name:
      - numix-icon-theme
      - numix-icon-theme-circle
    state: present
    update_cache: yes
    force_apt_get: yes

    #- name: Install Chrome
    #apt:
    #name:  https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    #state: present

- name: Install atom
  apt:
    deb: "https://atom-installer.github.com/v1.42.0/atom-amd64.deb?s=1576347951&ext=.deb"
    state: present
  when: atom|bool


- name: Install visual studio
  apt:
    deb: "https://az764295.vo.msecnd.net/stable/26076a4de974ead31f97692a0d32f90d735645c0/code_1.41.1-1576681836_amd64.deb"
    state: present
  when: visual|bool
