---
- name: Current kernel to var
  shell: uname -r
  register: kernel
- debug: var=kernel.stdout_lines

- name: Install necesary packages
  yum:
    name:
      - binutils
      - make
      - patch
      - libgomp
      - glibc-headers
      - glibc-devel
      - dkms
      - kernel-headers
      - kernel-devel
      - dkms
      - gcc

- name: VirtualBox Install
  block:
    - name: Instalar repo virtualbox
      yum_repository:
        name: virtualbox
        description: Fedora $releasever - $basearch - VirtualBox
        enabled: yes
        baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
        repo_gpgcheck: yes
        gpgcheck: yes
        gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
        state: present

    - name: "Install VirtualBox"
      yum:
        name:
          - VirtualBox-6.0
        state: present
        update_cache: yes

    - name: adding existing user to group
      user:
        name: "{{ user }}"
        groups: vboxusers
        append: yes

    - name: VBOX setup script
      shell: /usr/lib/virtualbox/vboxdrv.sh setup

    - name: Wait for
      wait_for:
        timeout: 20

  when: vbox|bool == True

- name: Install basic applications
  yum:
    name:
      - git
      - zsh
      - wget
      - curl
      - snapd
      - vim
      - vagrant
      # - vlc
      - gnome-tweak-tool
      - terminator
    state: present
    update_cache: yes

- name: Install Numix theme
  yum:
    name:
      - numix-icon-theme
      - numix-icon-theme-circle
      - numix-icon-theme-square
    state: present
    update_cache: yes

- name: Install Chrome
  yum:
    name:
      - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    state: present
    update_cache: yes

- name: Install atom
  dnf:
    name: https://atom-installer.github.com/v1.42.0/atom.x86_64.rpm?s=1576347968&ext=.rpm
    state: present
